# Use the below property if using service account credential authentication
#spring.cloud.gcp.credentials.location=file:src/main/resources/static/secret-key.json

service: vision-api-prototype-service
runtime: java
env: flex
handlers:
- url: /.*
  script: this field is required, but ignored
resources: 
  cpu: 2
  memory_gb: 5
  disk_size_gb: 10